Add assignment 2 files (without tests)
flerdacodeu/CodeU-2018-Group7 pull request #11
Opened 2018-06-05 17:07 UTC by lizaku

2018-06-07 07:33 UTC, ariava requested changes
Good job commenting your algorithms! Please have a look at my review.

2018-06-07 07:33 UTC, ariava commented on lizaku/assignment2/Q1.py
> +# In my solution I create classes for Node (for storing the key and the information about children;
Good job explaining your design choices!

2018-06-07 07:33 UTC, ariava commented on lizaku/assignment2/Q1.py
> +    # The algorithm is designed as follows: starting from the root, we recursively traverse the tree in pre-order.
Awesome explanation!

2018-06-07 07:33 UTC, ariava commented on lizaku/assignment2/Q1.py
> +        return None
Can you raise a KeyError when you don't find the key in the tree?
In Python, None is a perfectly valid value that could even be contained in a tree. The general rule is to raise an Error when an abnormal condition is detected.

2018-06-07 07:33 UTC, ariava commented on lizaku/assignment2/Q2.py
> +from Q1 import Node, BinaryTree, create_tree
Good job reusing the code!

2018-06-07 07:33 UTC, ariava commented on lizaku/assignment2/Q2.py
> +    # This algorithm is designed as follows: I start with the root and
Great explanation!

2018-06-07 07:33 UTC, ariava commented on lizaku/assignment2/Q2.py
> +        return None
Can you raise a KeyError when at least one of the values is not found in the tree?

2018-06-20 01:01 UTC, lizaku commented
Hello @ariava! Thank you for your suggestion about adding exceptions, I forgot about this possibility. Q1 is okay now, and with Q2 I still have problems: when both values are not found, it's alright, but when one value is found, it recursively returns and falls into the condition where the error is not raised. I don't know how to distinguish in this case between cases when one value is found I want to search in this subtree and when one value is found and another value is not found at all (so it's missing).

2018-08-03 09:39 UTC, ariava approved these changes
Awesome! Please feel free to merge this.

2018-08-03 09:55 UTC, merged