Add solution for assignment3
flerdacodeu/CodeU-2018-Group7 pull request #13
Opened 2018-06-18 23:03 UTC by nfadeeva

2018-06-19 10:40 UTC, ariava requested changes
Great job! Please have a look at my comments.

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/dictionary.py
> +    Dictionary class that looks like a trie
Super cool!

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/tests.py
> +    def test_is_word_true(self):
You can have more descriptive names, e.g. "test_word_is_in_dictionary" or "test_prefix_is_in_dictionary"

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/search_words.py
> +        self.r = len(cells)
Please use clearer names, e.g. "rows" and "columns"

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/search_words.py
> +                if x == i and y == j:
Can you merge the two ifs?

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/search_words.py
> +        if (x, y) not in used and dictionary.is_prefix(prefix + cells[x][y]):
Optimization: can you skip iterating on the neighbors if not dictionary.is_prefix(prefix)?

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/dictionary.py
> +    def __init__(self, data: List[str]):
Good job using annotations to clarify what you expect as an input!

2018-06-19 10:40 UTC, ariava commented on nfadeeva/assignment3/dictionary.py
> +    def put(self, word):
nit: use a different name. Conventionally, a method called "put" usually decreases a reference count on an object, it means that some user is no longer using that object. Here you are doing exactly the opposit.
You could call the method e.g. "add".

2018-06-20 10:26 UTC, nfadeeva commented on nfadeeva/assignment3/search_words.py
> +        self.r = len(cells)
@ariava  I've already fixed my code according to your comments, you can check it:)

2018-06-20 11:06 UTC, ariava approved these changes
Good job!

2018-06-20 11:07 UTC, merged