First assignment
flerdacodeu/CodeU-2018-Group7 pull request #6
Opened 2018-05-20 22:04 UTC by aliskin

2018-05-22 09:14 UTC, ariava requested changes
Nice job! Please have a look at my comments.

2018-05-22 09:14 UTC, ariava commented on aliskin/assignment1/anagram.py
> +def isAnagram(s, t, case_sensitive=True):
Please use the official function naming style: lowercase words separated by underscores.
See https://www.python.org/dev/peps/pep-0008/#function-and-variable-names.

2018-05-22 09:14 UTC, ariava commented on aliskin/assignment1/anagram.py
> +    for c in s:
You can also use a collections.Counter object to count occurrences of characters in words: https://docs.python.org/2/library/collections.html#collections.Counter

2018-05-22 09:28 UTC, ariava commented on aliskin/assignment1/kth-element.py
> +def kth_element(head, k):
It's "kth_last_element", that is the kth element starting from the last one going backwards.

2018-05-22 15:20 UTC, aliskin commented
Arianna, thanks for your comments!
I'm not sure if I updated the pull request properly.. hope it works!

2018-05-22 15:54 UTC, ariava requested changes

2018-05-22 15:54 UTC, ariava commented on aliskin/assignment1/anagram.py
> +def is_anagram(s, t, case_sensitive=True):
Can you add a few examples to show that the function really works? :)

2018-05-22 15:54 UTC, ariava commented on aliskin/assignment1/kth-element.py
> +def kth_last_element(head, k):
Can you add a few examples to show that the function really works? :)

2018-05-23 14:00 UTC, aliskin commented
Now the examples are there :)

2018-05-23 14:09 UTC, ariava approved these changes
Super!

2018-05-23 14:58 UTC, merged