Solutions for the second assignment
flerdacodeu/CodeU-2018-Group7 pull request #8
Opened 2018-05-30 14:43 UTC by aliskin

2018-06-07 07:09 UTC, ariava requested changes
Good job! Please have a look at my comments.

2018-06-07 07:09 UTC, ariava commented on aliskin/assignment2/lca.py
> +def find_lca(first_node, second_node):
Can you please add comments to the function and explain your algorithm?

2018-06-07 07:09 UTC, ariava commented on aliskin/assignment2/lca.py
> +class TreeNode():
Could you factor out the common class TreeNode and build_tree_from_preorder() in another file so you don't have to duplicate the code?

2018-06-07 08:38 UTC, aliskin commented
Arianna, I did what you asked. I renamed find_height function so probably the comment is not needed anymore.

2018-06-08 08:54 UTC, ariava approved these changes
Looks good! Good job!

2018-06-08 09:23 UTC, merged